apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: astarion
  name: member
spec:
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: astarion:member
          env:
          - name: PORT
            value: "8081"
          envFrom:
          - secretRef:
              name: astarion-db-connect-secret
      imagePullSecrets:
        - name: aws-ecr-secret
