apiVersion: v1
kind: Secret
metadata:
  namespace: astarion
  name: astarion-jwt-secret
type: Opaque
stringData:
  SECRET: "1BAsTAr10nRedUnDANt4uB1"

---

apiVersion: v1
kind: Secret
metadata:
  namespace: astarion
  name: astarion-db-connect-secret
type: Opaque
stringData:
  DB_HOST: "astarion-db.astarion.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "wjstjf"
  DB_USERNAME: "wjstjf"
  DB_PASSWORD: "wjstjf"

---

apiVersion: v1
kind: Secret
metadata:
  namespace: astarion
  name: astarion-db-secret
type: Opaque
stringData:
  MYSQL_DATABASE: "wjstjf"
  MYSQL_ROOT_PASSWORD: "wjstjf"
  MYSQL_USER: "wjstjf"
  MYSQL_PASSWORD: "wjstjf"
