apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: astarion
  name: astarion-db
spec:
  selector:
    matchLabels:
      app: astarion-db
  serviceName: astarion-db
  replicas: 1
  template:
    metadata:
      labels:
        app: astarion-db
    spec:
      containers:
        - name: astarion-db
          image: mysql:8.0
          args: ["--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci"]
          env:
          - name: LC_ALL
            value: C.UTF-8
          envFrom:
          - secretRef:
              name: astarion-db-secret
          volumeMounts:
            - name: astarion-db-init-sql-configmap
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: astarion-db-init-sql-configmap
          configMap:
            name: astarion-db-init-sql-configmap
